### ISSUE TITLE
Allow all types for the logs

### ISSUE THREAD

**Issue by JelleVos1** [JelleVos1/wase-engine#17]
**Is your feature request related to a problem? Please describe.**
Currently when you want to log an integer you can't. Currently only strings are allowed.

**Describe the solution you'd like**
Being allowed to log more than only strings.

**Additional context**
As an example, you can't do this currently or something similar.
`log_utils::info("Amount: " << number);`

There should be a way that it is possible to do this.

**Comment by AntonioCS** [comment]
Hey,
Have you tried using [spdlog](https://github.com/gabime/spdlog)?
It's on [vcpkg ](https://github.com/microsoft/vcpkg) (which is another thing you should think of using) and it will do what you want.
Ex.: 
```
spdlog::info("Hello {}. Today is the {}th time you visited", "Jello", 11101);
```
You can see it working [here](https://godbolt.org/z/bvzWasafb).

**Comment by JelleVos1** [comment]
> 
> 
> Hey,
> Have you tried using [spdlog](https://github.com/gabime/spdlog)?
> It's on [vcpkg ](https://github.com/microsoft/vcpkg) (which is another thing you should think of using) and it will do what you want.
> Ex.:
> 
> ```
> spdlog::info("Hello {}. Today is the {}th time you visited", "Jello", 11101);
> ```
> 
> You can see it working [here](https://godbolt.org/z/bvzWasafb).

Thank you so much for the tips. I had never heard about vcpkg before but I looked at it a bit and it seems really good, I will look further into it. I will look into spdlog as well. Massive thanks!

**Comment by AntonioCS** [comment]
No worries.
You can take a look at it being used here: https://github.com/AntonioCS/CppProjectSamples
Simple templates on how to use it (not the only way)

**Comment by RajeckMassa** [comment]
Maybe I don't understand the question exactly, but isn't [https://en.cppreference.com/w/cpp/language/templates](this) exactly what you're looking for?
